github_actions_object_id = "61d850ea-a0df-410f-9c58-99ef8b77ecac"
subscription_id = "249471bf-b8ae-4c8a-abf4-f9e67509e192"

resource_group_name         = "freesarkozy"
resource_group_location     = "francecentral"
sa_account_tier             = "Standard"
sa_account_replication_type = "LRS"
sa_name                     = "freesarkozy"
ws_name                     = "freesarkozy"
ai_name                     = "freesarkozy"
asp_name                    = "freesarkozy"
fa_name                     = "freesarkozy"
runtime_name                = "python"
runtime_version             = "3.11"
cosmos_account_name         = "freesarkozy"